AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Style/FrozenStringLiteralComment:
  Enabled: false

# This one has a bug https://github.com/rubocop-hq/rubocop/issues/7397
Style/SafeNavigation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

# Style/ClassAndModuleChildren:
#   Enabled: false

# Metrics/ClassLength:
#   Enabled: false
